### ISSUE TITLE
throw is not necessary

### ISSUE THREAD

**Issue by EmileVinsonneau** [sandrock/SrkToolkit#19]
https://github.com/sandrock/SrkToolkit/blob/08b6dec99a7c488cdb053a636e23a161b97ac514/Sources/NET4.SrkToolkit.Common/System/StringTransformer.cs#L335

The following code seem to work in state.

**Comment by sandrock** [comment]
fixed in commit 7e3475f706fc77997922f3d7b493e8647d257d7d  
available in 1.2.143
